name: Simulazione Esercizio 1
on: 
  workflow_dispatch:
  # Mettendo inputs quando lo lancio posso scegliere il valore da dare a ordine_valido
    inputs:
      ordine_valido:
        description: "true se l'ordine e valido"
        required: true
        default: "true"

jobs:
  validazione_ordine:
    runs-on: ubuntu-latest
    
    outputs: 
      ordine_valido: ${{ steps.controllo.outputs.ordine_valido }}
      
    steps:
      - run: echo "Validando l'ordine..."
      
      # Assegniamo l'output fisicamente usando un 'id'
      - id: controllo
      # Avendo aggiunto inputs, ora recupero il valore in maniera dinamica, vado a vedere l'evento che ha fatto scattare il processo
      # ovvero vado a vedere quello che è il valore che ho dato a ordine_valido
        run: echo "ordine_valido=${{ github.event.inputs.ordine_valido }}" >> $GITHUB_OUTPUT 
        
      - run: sleep 10

  prepara_spedizione:
    runs-on: ubuntu-latest
    needs: validazione_ordine

    if: needs.validazione_ordine.outputs.ordine_valido == 'true'
    
    steps:
      - run: echo "Ordine valido! Preparo la spedizione..."
      - run: sleep 5

  notifica_errore:
    runs-on: ubuntu-latest
    needs: validazione_ordine
    if: needs.validazione_ordine.outputs.ordine_valido == 'false'

    steps:
      - run: echo "Ordine non valido! Qualcosa è andato storto..."
      - run: sleep 5

    
